### ISSUE TITLE
Account Metrics having a null exception when theme is not yet loaded

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/BatchExplorer#1648]
```
TypeError:
   at datasets.response.metrics.map (at datasets.response.metrics.map (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:225339:42)at datasets.response.metrics.map (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:225339:42): file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.jsat datasets.response.metrics.map (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:225339:42): 225339)
   at SafeSubscriber._sub.obs.subscribe.response [as _next] (at SafeSubscriber._sub.obs.subscribe.response [as _next] (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:225338:46)at SafeSubscriber._sub.obs.subscribe.response [as _next] (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:225338:46): file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.jsat SafeSubscriber._sub.obs.subscribe.response [as _next] (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:225338:46): 225338)
   at SafeSubscriber.__tryOrUnsub (at SafeSubscriber.__tryOrUnsub (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71713:16)at SafeSubscriber.__tryOrUnsub (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71713:16): file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.jsat SafeSubscriber.__tryOrUnsub (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71713:16): 71713)
   at SafeSubscriber.next (at SafeSubscriber.next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71651:22)at SafeSubscriber.next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71651:22): file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.jsat SafeSubscriber.next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71651:22): 71651)
   at Subscriber._next (at Subscriber._next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71595:26)at Subscriber._next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71595:26): file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.jsat Subscriber._next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71595:26): 71595)
   at Subscriber.next (at Subscriber.next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71572:18)at Subscriber.next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71572:18): file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.jsat Subscriber.next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71572:18): 71572)
   at RefCountSubscriber.Subscriber._next (at RefCountSubscriber.Subscriber._next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71595:26)at RefCountSubscriber.Subscriber._next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71595:26): file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.jsat RefCountSubscriber.Subscriber._next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71595:26): 71595)
   at RefCountSubscriber.Subscriber.next (at RefCountSubscriber.Subscriber.next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71572:18)at RefCountSubscriber.Subscriber.next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71572:18): file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.jsat RefCountSubscriber.Subscriber.next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:71572:18): 71572)
   at Subject.next (at Subject.next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:137741:25)at Subject.next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:137741:25): file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.jsat Subject.next (file:///C:/Program%20Files/BatchExplorer/resources/app.asar/build/app.f3b72a2af9ff9cd512ab.bundle.js:137741:25): 137741)
```

**Comment by timotheeguerin** [comment]
Believe the issue is due to the theme loading slower than the metrics??
