### ISSUE TITLE
Python backend not working on latest release

### ISSUE THREAD

**Issue by davidkydd** [Azure/BatchExplorer#2384]
**Describe the bug**
"Python backend disconnected" in release 2.11, breaks all applications in the Gallery.

**To Reproduce**
Install latest release 2.11, Login, "Python backend disconnected" shows in bottom title bar

**Logs**
Navigating to %APPDATA%\BatchExplorer\logs and then opening the most recent python-server.log file shows the following error, which looks related to dependencies:
 
info: ========================= STARTING PYTHON RPC SERVER PROCESS =========================
info: Traceback (most recent call last):
  File "main.py", line 32, in <module>
  File "main.py", line 26, in run
  File "server\websocket_server.py", line 17, in __init__
  File "site-packages\websockets\imports.py", line 81, in __getattr__
  File "site-packages\websockets\imports.py", line 26, in import_name
ModuleNotFoundError: No module named 'websockets.legacy'
[10356] Failed to execute script main

**Version (please complete the following information):**
 - OS: Windows
 - Version 2.11

**Comment by themorey** [comment]
I'm having the same issue on Mac OSX 12.0.1 Monterey.  

app.log
```
{"0":"Invalid unit value NaN","level":"error","message":"[BL] Uncaught exception:","timestamp":"2021-11-15T01:41:49.813Z"}
{"level":"info","message":"Websocket connection closed. Retrying to connect in 32s","timestamp":"2021-11-15T01:41:53.587Z"}
```

python.server.log
```
info: ========================= STARTING PYTHON RPC SERVER PROCESS =========================
info: Traceback (most recent call last):
  File "main.py", line 32, in <module>
  File "main.py", line 26, in run
  File "server/websocket_server.py", line 17, in __init__
  File "websockets/imports.py", line 81, in __getattr__
  File "websockets/imports.py", line 26, in import_name
ModuleNotFoundError: No module named 'websockets.legacy'
[93271] Failed to execute script main
```

**Comment by dpwatrous** [comment]
I see the same issue as well. Looking into it

**Comment by dpwatrous** [comment]
It looks like some changes the websockets library made to add lazy module loading made PyInstaller stop including some critical files in the build. Switching the imports around fixed the issue. PR #2411
