### ISSUE TITLE
MSAL-node ClientAuthError: network_error: Network request failed.

### ISSUE THREAD

**Issue by san-goyal** [Azure/BatchExplorer#2403]
**Describe the bug**
@azure/msal-node library throws error intermittently while retrieving access token using client credential code auth.

**Code**
```
const msal = require('@azure/msal-node');
        const config = {
            auth: {
                clientId: <<client id>>,
                authority: "https://login.microsoftonline.com/<<tenantID>>/",
                clientSecret: <<client secret>>,
                knownAuthorities: ["https://login.microsoftonline.com/<<tenantID>>/"]
            },
            system: {
                loggerOptions: {
                    loggerCallback(loglevel, message, containsPii) {
                        console.log(message);
                    },
                    piiLoggingEnabled: false,
                    logLevel: msal.LogLevel.Error,
                }
            }
        };
    
        const cca = new msal.ConfidentialClientApplication(config);
        const clientCredentialRequest = {
            scopes: ["https://graph.microsoft.com/.default"],
        };
        cca.acquireTokenByClientCredential(clientCredentialRequest).then((response) => {
            resolve(response.accessToken);
        }).catch((error) => {
            console.log(JSON.stringify(error));
            reject(error);
        })       
```
**Error**
```
Exception while executing function: Functions.QueueTriggerFunction Result: Failure
Exception: ClientAuthError: network_error: Network request failed. Please check network trace to determine root cause. | Fetch client threw: Error: connect ETIMEDOUT 20.190.159.132:443 | Attempted to reach: https://login.microsoftonline.com/<<tenantid>>/oauth2/v2.0/token
Stack: ClientAuthError: network_error: Network request failed. Please check network trace to determine root cause. | Fetch client threw: Error: connect ETIMEDOUT 20.190.159.132:443 | Attempted to reach: https://login.microsoftonline.com/<<tenantid>>/oauth2/v2.0/token
at ClientAuthError.AuthError [as constructor] (D:\home\site\wwwroot\node_modules\@azure\msal-common\dist\index.cjs.js:477:24)
at new ClientAuthError (D:\home\site\wwwroot\node_modules\@azure\msal-common\dist\index.cjs.js:729:28)
at Function.ClientAuthError.createNetworkError (D:\home\site\wwwroot\node_modules\@azure\msal-common\dist\index.cjs.js:772:16)
at NetworkManager.<anonymous> (D:\home\site\wwwroot\node_modules\@azure\msal-common\dist\index.cjs.js:3049:51)
at step (D:\home\site\wwwroot\node_modules\@azure\msal-common\dist\index.cjs.js:79:23)
at Object.throw (D:\home\site\wwwroot\node_modules\@azure\msal-common\dist\index.cjs.js:60:53)
at rejected (D:\home\site\wwwroot\node_modules\@azure\msal-common\dist\index.cjs.js:51:65)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Expected behavior**
Access token should be returned every time.

**Version (please complete the following information):**
 - Azure function v3
 - Node v14
 - Language JavaScript
 - Library `@azure/msal-node": "^1.5.0"`

**Comment by san-goyal** [comment]
Closing the issue. Raised again on correct project.
